db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/webook_intr"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
#  启动监听 8090 端口
  addr: ":8094"

migrator:
  http:
    addr: ":8082"
